movie_name = "test"
movie_length = 1

[effects]
  [effects.3]
    effect_name = "air"
    length_ms = 2
  [effects."1.5"]
    effect_name = "air"
    length_ms = 2000
  [effects."8.5"]
    effect_name = "air"
    length_ms = 500
