movie_name = "test"
movie_length = 1

[effects]
  [effects.2]
    effect_name = "air"
    length_ms = 500
  [effects.4]
    effect_name = "air"
    length_ms = 1000
  [effects.6]
    effect_name = "air"
    length_ms = 500
