movie_name = "La Casa De Papel (2017)"
movie_length = 120

[effects]
  [effects.102]
    effect_name = "effect"
    length_ms = 0
  [effects.2223]
    effect_name = "test"
    length_ms = 444
  [effects.232]
    effect_name = "effect"
    length_ms = 0
